/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.JdbiDaoFactory;
import dao.ProductCollectionsDAO;
import dao.ProductDAO;
import domain.Product;
import helpers.SimpleListModel;
import java.util.Collection;

/**
 *
 * @author benforde
 */
public class ProductViewer extends javax.swing.JDialog {
    ProductDAO dao = JdbiDaoFactory.getProductDAO();
    SimpleListModel productsModel = new SimpleListModel(); 
    SimpleListModel categoriesModel = new SimpleListModel(); 
    
    

    /**
     * Creates new form ProductViewer
     * @param parent
     * @param modal
     */
    public ProductViewer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        Collection<Product> products = dao.getProducts();
        productsModel.updateItems(products);
        listProducts.setModel(productsModel);
        Collection categories = dao.getCategories(); 
        categoriesModel.updateItems(categories); 
        catagoryFilterVal.setModel(categoriesModel); 
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        closeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        veiwProductsJlable = new javax.swing.JLabel();
        searchIdLable = new javax.swing.JLabel();
        idSearchValue = new javax.swing.JTextField();
        searchID = new javax.swing.JButton();
        catagroyJlable = new javax.swing.JLabel();
        catagorySearchB = new javax.swing.JButton();
        catagoryFilterVal = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listProducts);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit ");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        veiwProductsJlable.setText("veiw Products");

        searchIdLable.setText("Search ID");

        idSearchValue.setText("enter ID");
        idSearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSearchValueActionPerformed(evt);
            }
        });

        searchID.setText("search");
        searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDActionPerformed(evt);
            }
        });

        catagroyJlable.setText("Filter by catagory");

        catagorySearchB.setText("search");
        catagorySearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagorySearchBActionPerformed(evt);
            }
        });

        catagoryFilterVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryFilterValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(searchIdLable)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(veiwProductsJlable)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(idSearchValue)
                                .addGap(18, 18, 18)
                                .addComponent(searchID))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton)
                                .addGap(54, 54, 54)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(catagroyJlable)
                                .addGap(18, 18, 18)
                                .addComponent(catagoryFilterVal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(catagorySearchB)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(veiwProductsJlable)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchIdLable)
                    .addComponent(idSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catagroyJlable)
                    .addComponent(catagorySearchB)
                    .addComponent(catagoryFilterVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton)
                    .addComponent(closeButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        
        dispose(); 
        
    }//GEN-LAST:event_closeButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Product p1 = (Product)listProducts.getSelectedValue(); 
        dao.removeProduct(p1);
        productsModel.updateItems(dao.getProducts());
        
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void idSearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSearchValueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idSearchValueActionPerformed

    private void searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDActionPerformed
        // TODO add your handling code here:
        String id = idSearchValue.getText();
        Product item = dao.searchById(id); 
        productsModel.updateItems(item);
       
    }//GEN-LAST:event_searchIDActionPerformed

    private void catagorySearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagorySearchBActionPerformed
        // TODO add your handling code here:
        String catagoryFilter = (String) catagoryFilterVal.getSelectedItem(); 
        Collection<Product> item = dao.filterByCatagorie(catagoryFilter); 
        productsModel.updateItems(item);
    }//GEN-LAST:event_catagorySearchBActionPerformed

    private void catagoryFilterValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryFilterValActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_catagoryFilterValActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catagoryFilterVal;
    private javax.swing.JButton catagorySearchB;
    private javax.swing.JLabel catagroyJlable;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField idSearchValue;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Product> listProducts;
    private javax.swing.JButton searchID;
    private javax.swing.JLabel searchIdLable;
    private javax.swing.JLabel veiwProductsJlable;
    // End of variables declaration//GEN-END:variables
}
